dist: bionic
addons:
  apt:
    update: true
    packages:
      - chef-workstation

branches:
  only:
    - master

services: docker

jobs:
  include:
    - env: INSTANCE=default-ubuntu-1804

script: KITCHEN_LOCAL_YAML=./api_app/kitchen.dokken.yml kitchen verify ${INSTANCE}
